### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by aetherwu** [marcoagner/Flask-QRcode#12]
AssertionError: A setup function was called after the first request was handled.  This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late.
To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests.

PY FILE
@app.router(...)
def someview():
from flask.ext.qrcode import QRcode
QRcode(app)
return render_template("qr.html",url=request.url)

TEMPLATE
<img src="{{ url }}">

**Comment by agnerio** [comment]
Thank you. I will have a look on the issue you are having and update this issue with further information.
