### ISSUE TITLE
Testing suite

### ISSUE THREAD

**Issue by marcoagner** [marcoagner/Flask-QRcode#15]
It must follow item 2. on http://flask.pocoo.org/docs/0.11/extensiondev/#approved-extensions:

> 2. It must ship a testing suite that can either be invoked with make test or python setup.py test. For test suites invoked with make test the extension has to ensure that all dependencies for the test are installed automatically. If tests are invoked with python setup.py test, test dependencies can be specified in the setup.py file. The test suite also has to be part of the distribution.

**Comment by 1dot75cm** [comment]
I completed a test suite in [PR16](https://github.com/marcoagner/Flask-QRcode/pull/16). It may be not best, but work fine. @marcoagner

**Comment by marcoagner** [comment]
Thanks! Solved.
