### ISSUE TITLE
latest release is wrong in PYPI

### ISSUE THREAD

**Issue by 1dot75cm** [marcoagner/Flask-QRcode#17]
Currently the latest release is `0.8.0`, but `pip` think `1.0` is the newest release. @marcoagner 

```
$ pip install -v -U Flask-QRcode
Installed version (1.0) is most up-to-date (past versions:
 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 1.0)
...
Successfully installed Flask-QRcode-1.0
```

**Comment by marcoagner** [comment]
Thank you for the heads up. My bad!
Closing this since it's solved but let me know if I missed something again. (think I did not)

**Comment by 1dot75cm** [comment]
Testing pass. It's works fine.  Thank you. 👍
