### ISSUE TITLE
Pass qrcode content as arg

### ISSUE THREAD

**Issue by steve-heslouin** [marcoagner/Flask-QRcode#21]
Hi, 

I would like to know if its possible to do as follow:

```render_template('sample_application.html', message = message)```

And on the template insert the message for the qrcode instead of hardcoding it directly on the html?

I tried many workarounds, but none of them works :/

Thanks a lot :)

**Comment by steve-heslouin** [comment]
shame ;)

``` <img src="{{ qrcode(message) }}"> ``` :)

**Comment by marcoagner** [comment]
No problem! Thank you for reporting.
