### ISSUE TITLE
Generating Unreadable QR Codes

### ISSUE THREAD

**Issue by videah** [marcoagner/Flask-QRcode#22]
Any code I try to generate isn't picked up by any reader. The corners don't look right to me. Here's an example "Hello World" code.

![image](https://user-images.githubusercontent.com/4761786/39997431-d6bae7de-577a-11e8-91d7-9c340d27ba76.png)

**Comment by marcoagner** [comment]
Thank you for reporting this issue. 
What version of Flask-QRcode and python-qrcode are you using?
Package `qrcode==6.0` introduced a breaking change that caused this issue and `Flask-QRcode==2.0.0` was released to be compatible with the breaking change introduced.
Please, see https://github.com/marcoagner/Flask-QRcode/issues/20 for more information.

**Comment by videah** [comment]
I was using qrcode-5.3, upgrading to 6.0 fixed the issue. Thanks for pointing me in the right direction.
