### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by DataDrug** [marcoagner/Flask-QRcode#23]
Hey guys,

I'm using Flask Admin (https://github.com/jonalxh/Flask-Admin-Dashboard) and I have a doubt.

Let's say that I have a Model with:

Product
Serial Number
Model Number

And I would like to add a new Column that would generate a QR Code based on Product+Serial+Model Number.

Is this even possible?

Can someone point me to the right direction?

Thank you very much.

P.S: I'm learning python so please excuse me if this is a basic issue that I'm wasting your time with.

**Comment by marcoagner** [comment]
Closing this as it is Flask-Admin related.

Nevertheless, you can certainly customize one of the Admin's columns with the content you want.
I believe one way could be to override the ModelView's `_list_thumbnail` and return `Markup("<img src={{ qrcode(Product+Serial+Model }}.../>)` but maybe there's something simpler.
