### ISSUE TITLE
proper documents 

### ISSUE THREAD

**Issue by hoomanist** [marcoagner/Flask-QRcode#27]
why there is not a complete documents of methods and classes and usage?it is really difficult to use it this way

**Comment by marcoagner** [comment]
In which way do you want to use it that's not addressed by [this](https://marcoagner.github.io/Flask-QRcode/#basic-usage) and docstrings?

**Comment by marcoagner** [comment]
For the record, the link does not contain a complete doc of methods and classes. It shows only end usage for Jinja2 templates.

**Comment by hoomanist** [comment]
> In which way do you want to use it that's not addressed by [this](https://marcoagner.github.io/Flask-QRcode/#basic-usage)?

that was think i was searching for thanks
