### ISSUE TITLE
Rendering an icon inside the QR code

### ISSUE THREAD

**Issue by UBassi** [marcoagner/Flask-QRcode#40]
Problem when rendering icon.
A fix is required in \_\_init\_\_.py:

`icon = icon.resize((int(icon_w), int(icon_h)), Image.LANCZOS)`
I/O
`icon = icon.resize((int(icon_w), int(icon_h)), Image.ANTIALIAS)`

(ANTIALIAS removed in Pillow 10.0.0)

**Comment by racinmat** [comment]
I'll try to get to it tomorrow.

**Comment by racinmat** [comment]
done, let me know if everything is ok

**Comment by connorhess** [comment]
Cool, will pull latest and relay back. Appreciate it🙌
