### ISSUE TITLE
Sample not working.

### ISSUE THREAD

**Issue by iJebus** [marcoagner/Flask-QRcode#6]
Running the sample application, it seems to not be working. I get a 'TypeError: 'exceptions.IOError' object is not callable' error and on refresh the page loads with a broken image.

**Comment by vimalloc** [comment]
Is this still in the works? We had the same issues with the patch provided by @pmccallum fixing everything perfectly. It would be awesome to see it merged, if there aren't any issues :+1:

**Comment by marcoagner** [comment]
@vimalloc , I think @pmccallum solution is much better and implemented it on a separated branch called "pmccallum-io-fix" for now.

Now... Importing StringIO introduces incompatibility with Python3 which doesn't have such module (it uses "io.StringIO"). I'd like to support both 2 (after 2.6 at least) and 3 before merging but if the choice is needed I personally prefer supporting 3. I'll check if this is sanely feasible to support both on this case or if it's just a bad idea.
I apprecciate any help on this choice and @pmccallum better solution will be kept whatever the support decision.
