### ISSUE TITLE
does not work with python 3 because of StringIO module

### ISSUE THREAD

**Issue by dnano91** [marcoagner/Flask-QRcode#8]
Trying to use this module with a python3 project only resolves in an Error: No module named 'StringIO'
After a quick search I found this: http://stackoverflow.com/questions/11914472/stringio-in-python3
Aparently that module is no longer available, but its classes are in 'io'

**Comment by dnano91** [comment]
fixed in pull request #10

**Comment by marcoagner** [comment]
Closing and this https://github.com/marcoagner/Flask-QRcode/pull/11 solves.
Thank you for your PR and sorry for my delay on this.
Feel free to contribute and test, please. Thanks!
